package cp.server.common;

public enum JobType
{
    HOTCOMMENTBYTYPE, HOTCOMMENT, KEYWORDFINDER, SINAPAGELOADER, TENCENTPAGELOADER, NETEASEPAGELOADER, SOHUPAGELOADER, SINACOMMENTOPER, NETEASECOMMENTOPER, FILEUPLOADER;
}
